### PR TITLE
[fix #122] Avoid Sprockets deprecations

### LINKED ISSUE #122: deprecation warning at 'rails s'
guys, 
when i start app in development mode i receive this deprecation warnings 
actually all seems to run fine, but not production deployment tests have been done yet!!

```
=> Booting WEBrick
=> Rails 4.2.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /home/francesco/.rvm/gems/ruby-2.2.2@crm_2016/bundler/gems/less-rails-05186ebeea3a/lib/less/rails/railtie.rb:16)
DEPRECATION WARNING: You are using the a deprecated processor interface Less::Rails::ImportProcessor.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /home/francesco/.rvm/gems/ruby-2.2.2@crm_2016/bundler/gems/less-rails-05186ebeea3a/lib/less/rails/railtie.rb:21)
[2016-07-22 11:24:33] INFO  WEBrick 1.3.1
[2016-07-22 11:24:33] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
[2016-07-22 11:24:33] INFO  WEBrick::HTTPServer#start: pid=22380 port=3000
```

i think something is running bad during initialization against sprocket v.3.7.0...
available to give you more info if needed....

waiting your suggestions

regards
francesco

### PR DESCRIPTION
**Pull request by MustafaZain**
- Use both 'register_engine' and 'register_transformer' in railtie.rb

### CODE REVIEW

**Comment by Genkilabs** [comment]
@MustafaZain check out some tweaks that @nonrational and I have added to your branch.
Commented here: https://github.com/metaskills/less-rails/issues/122#issuecomment-264285405

**Comment by kreintjes** [comment]
@MustafaZain works great, thanks! Tests seem to fail though.

**Comment by MustafaZain** [comment]
@kreintjes yeah I didn't edit test code but I tried it myself as it's a temp solution for deprecation warning.

**Comment by Mirv** [comment]
Where does  @kreintjes  where does this stand?  Does there need to be a fork for rails 5 & the less-rails to continue to advance?  The game is still posting errors about misusing the sprockets gem months later.

**Comment by kreintjes** [comment]
@Mirv I have no idea. I am no maintainer of either less-rails or rails itself. I simply have an application running Rails with less-rails which I recently updated to Rails 5. I got a bunch of deprecation warnings, and I used @MustafaZain's fork to fix them. It works, but I am afraid his PR will not be merged, as long as the CI does not pass.

**Comment by Mirv** [comment]
@kreintjes roger - apologies - was following the trail & didn't check to see if you were actually enabled as maintainer!

**Comment by brendon** [comment]
@MustafaZain, the test suite is failing because Rails 5 doesn't support any of the Rubies in the current testing matrix. Edit the `travis.yml` file and `Appraisals` file to add in testing against newer Rails versions and Ruby versions. We did this at `acts_as_list` and it works well. You need to add exclusions for Ruby versions on Rails 5:

https://github.com/swanandp/acts_as_list/blob/master/.travis.yml
https://github.com/swanandp/acts_as_list/blob/master/Appraisals

Read the docs on `Appraisals` as you need to run a command to interpret the `Appraisals` file into individual `gemfiles`.

@simi, would you be keen to merge this if @MustafaZain can get the suite up to date and running?

Reference: #122

**Comment by madmax** [comment]
For me this path don't works. 

I get 
    undefined method `call' for Less::Rails::ImportProcessor:Class
    Did you mean?  caller

Full backtrace:

`sprockets (3.7.1) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.7.1) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.7.1) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.7.1) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
sprockets (3.7.1) lib/sprockets/loader.rb:44:in `load'
sprockets (3.7.1) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.7.1) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.7.1) lib/sprockets/bundle.rb:23:in `block in call'
sprockets (3.7.1) lib/sprockets/utils.rb:200:in `dfs'
sprockets (3.7.1) lib/sprockets/bundle.rb:24:in `call'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.7.1) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.7.1) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.7.1) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.7.1) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
sprockets (3.7.1) lib/sprockets/loader.rb:44:in `load'
sprockets (3.7.1) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.7.1) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.7.1) lib/sprockets/base.rb:66:in `find_asset'
sprockets (3.7.1) lib/sprockets/base.rb:92:in `[]'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:355:in `find_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:336:in `digest_path'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:325:in `asset_path'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:102:in `block in resolve_asset_path'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `each'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `detect'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `resolve_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:101:in `resolve_asset_path'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
actionview (4.2.8) lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
actionview (4.2.8) lib/action_view/helpers/asset_url_helper.rb:267:in `stylesheet_path'
actionview (4.2.8) lib/action_view/helpers/asset_tag_helper.rb:100:in `block in stylesheet_link_tag'
actionview (4.2.8) lib/action_view/helpers/asset_tag_helper.rb:96:in `map'
actionview (4.2.8) lib/action_view/helpers/asset_tag_helper.rb:96:in `stylesheet_link_tag'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:185:in `block in stylesheet_link_tag'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:183:in `map'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:183:in `stylesheet_link_tag'
app/views/layouts/application/_head.html.erb:3:in `_app_views_layouts_application__head_html_erb__3362089814668164909_70162304153440'
actionview (4.2.8) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.8) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.8) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.8) lib/action_view/template.rb:143:in `render'
actionview (4.2.8) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
actionview (4.2.8) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
actionview (4.2.8) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.8) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.8) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.8) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.8) lib/action_view/renderer/partial_renderer.rb:309:in `render'
actionview (4.2.8) lib/action_view/renderer/renderer.rb:51:in `render_partial'
actionview (4.2.8) lib/action_view/helpers/rendering_helper.rb:35:in `render'
app/views/layouts/application.html.erb:4:in `_app_views_layouts_application_html_erb___4205754798311119765_70162305711560'
actionview (4.2.8) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.8) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.8) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.8) lib/action_view/template.rb:143:in `render'
actionview (4.2.8) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
actionview (4.2.8) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.8) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.8) lib/action_view/renderer/renderer.rb:46:in `render_template'
actionview (4.2.8) lib/action_view/renderer/renderer.rb:27:in `render'
actionview (4.2.8) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.8) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.8) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.8) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.8) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.8) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.8) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.2.8) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/madmax/.rbenv/versions/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (4.2.8) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (4.2.8) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (4.2.8) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (4.2.8) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (4.2.8) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.8) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.8) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.8) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.8) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.8) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.8) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.8) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.8) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.8) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.8) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.8) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.8) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.8) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.8) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.8) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.8) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.8) lib/action_dispatch/routing/route_set.rb:817:in `call'
omniauth (1.1.4) lib/omniauth/strategy.rb:184:in `call!'
omniauth (1.1.4) lib/omniauth/strategy.rb:164:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.5) lib/rack/etag.rb:24:in `call'
rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.5) lib/rack/head.rb:13:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.8) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.8) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.8) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.8) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.8) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.8) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.8) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.8) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.5) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.8) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.5) lib/rack/lock.rb:17:in `call'
actionpack (4.2.8) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
rack-utf8_sanitizer (1.3.0) lib/rack/utf8_sanitizer.rb:15:in `call'
railties (4.2.8) lib/rails/engine.rb:518:in `call'
railties (4.2.8) lib/rails/application.rb:165:in `call'
rack (1.6.5) lib/rack/lock.rb:17:in `call'
rack (1.6.5) lib/rack/content_length.rb:15:in `call'
rack (1.6.5) lib/rack/handler/webrick.rb:88:in `service'
/Users/madmax/.rbenv/versions/2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/Users/madmax/.rbenv/versions/2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/Users/madmax/.rbenv/versions/2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'`

**Comment by brendon** [comment]
That's better :) Now there are just a few failures to deal with. And LOTS! of warnings that could also be dealt with unless they're coming from the gems...

**Comment by simi** [comment]
fixed in 3.0

**Pull request closed without merging**
