### PR TITLE
[CI] Test against Ruby 2.5

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by metaskills** [comment]
Thanks for taking the time to do that. Merging now.

**Comment by simi** [comment]
I was just wondering if Rails 4.0 supports Ruby 2.5.

**Comment by nicolasleger** [comment]
Rails 4.0 and 4.1 fails for Ruby 2.5 with same errors as Ruby 2.4.
See https://travis-ci.org/nicolasleger/less-rails/builds/345249359

**Comment by nicolasleger** [comment]
http://weblog.rubyonrails.org/2017/2/21/Rails-4-2-8-has-been-released/
> This is the first version of the 4.2 series that officially support Ruby 2.4.

**Pull request merged**
