### PR TITLE
Fix NoMethodError in app.assets.register_preprocessor.

### PR DESCRIPTION
**Pull request by ccallebs**
When running Rails 5 alpha and attempting to use the twitter-bootstrap-rails gem, I encountered the following error when trying to run `rails generate bootstrap:install less`.

```
/Users/chuck/.rvm/gems/ruby-2.2.2@tcg/gems/less-rails-2.7.0/lib/less/rails/railtie.rb:19:in `block in <class:Railtie>': undefined method `register_preprocessor' for nil:NilClass (NoMethodError)
	from /Users/chuck/.rvm/gems/ruby-2.2.2@tcg/bundler/gems/rails-52cf1a71b393/railties/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/chuck/.rvm/gems/ruby-2.2.2@tcg/bundler/gems/rails-52cf1a71b393/railties/lib/rails/initializable.rb:30:in `run'
	from /Users/chuck/.rvm/gems/ruby-2.2.2@tcg/bundler/gems/rails-52cf1a71b393/railties/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/chuck/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/chuck/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/chuck/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/chuck/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/chuck/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/chuck/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/chuck/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/chuck/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/chuck/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/chuck/.rvm/gems/ruby-2.2.2@tcg/bundler/gems/rails-52cf1a71b393/railties/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/chuck/.rvm/gems/ruby-2.2.2@tcg/bundler/gems/rails-52cf1a71b393/railties/lib/rails/application.rb:352:in `initialize!'
	from /Users/chuck/Code/Ruby/tcg/config/environment.rb:5:in `<top (required)>'
	from /Users/chuck/.rvm/gems/ruby-2.2.2@tcg/bundler/gems/rails-52cf1a71b393/railties/lib/rails/application.rb:328:in `require'
	from /Users/chuck/.rvm/gems/ruby-2.2.2@tcg/bundler/gems/rails-52cf1a71b393/railties/lib/rails/application.rb:328:in `require_environment!'
	from /Users/chuck/.rvm/gems/ruby-2.2.2@tcg/bundler/gems/rails-52cf1a71b393/railties/lib/rails/commands/commands_tasks.rb:147:in `require_application_and_environment!'
	from /Users/chuck/.rvm/gems/ruby-2.2.2@tcg/bundler/gems/rails-52cf1a71b393/railties/lib/rails/commands/commands_tasks.rb:133:in `generate_or_destroy'
	from /Users/chuck/.rvm/gems/ruby-2.2.2@tcg/bundler/gems/rails-52cf1a71b393/railties/lib/rails/commands/commands_tasks.rb:51:in `generate'
	from /Users/chuck/.rvm/gems/ruby-2.2.2@tcg/bundler/gems/rails-52cf1a71b393/railties/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/chuck/.rvm/gems/ruby-2.2.2@tcg/bundler/gems/rails-52cf1a71b393/railties/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
I found that app.assets was nil and thusly no longer had a "register_preprocessor" method. The fix was simple enough, but if the API has changed in Rails 5 the problem may go deeper.

### CODE REVIEW

**Comment by maxd** [comment]
Your PR don't resolve problem. It just covert one error to other.

I think you are using Sprockets 4.x where Tilt is deprecated. So, it doesn't have `register_preprocessor` method. Which version of Sprockets are you using?

**Comment by ccallebs** [comment]
@maxd Sprockets 3.2. Which error did it convert to? It seemed to be working fine on my Rails 5 project.

**Comment by maxd** [comment]
> Which error did it convert to?

`NoMethodError` to `NoPreprocessorHandler`

> It seemed to be working fine on my Rails 5 project.

Look at you PR carefully. You removed all calls of `register_preprocessor` method i.e. registration of `ImportProcessor`. So, why do you think that all works fine after that? :smile:

Try to investigate why `app.assets` is `nil`. This is root of your problem.

**Comment by ccallebs** [comment]
@maxd Gotcha, will do. It was a fix that just allowed the generation of the assets for me so I rode with it :)

I'll do some more digging on this, as other gems seem to have the same issue. Maybe I can fix it at its core.

**Comment by grauschnabel** [comment]
I got the same problem here after an bundle update.  what do I have to do now?

**Comment by betesh** [comment]
What's the solution here?  Now that sprockets-rails 3.0.0 was released, I am getting the same error.

**Comment by blmundie** [comment]
+1

**Comment by Ranger-X** [comment]
Quick and dirty workaround (in config/application.rb):
`YourApp::Application.assets = Sprockets::Railtie.build_environment(YourApp::Application, true)`

**Comment by kilimchoi** [comment]
`YourApp::Application.assets = Sprockets::Railtie.build_environment(YourApp::Application, true)` didn't work for me.

**Comment by simi** [comment]
Thanks for PR. We're working on the fix in #112.

**Pull request closed without merging**
